// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SporBeslenmeWeb.Data;

#nullable disable

namespace SporBeslenmeWeb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260328145033_TarifGorselEsnetme")]
    partial class TarifGorselEsnetme
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SporBeslenmeWeb.Models.Egzersizler", b =>
                {
                    b.Property<int>("EgzersizID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EgzersizID"));

                    b.Property<string>("Ad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GorselYolu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KasGrupID")
                        .HasColumnType("int");

                    b.Property<string>("NasilYapilir")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoYolu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZorlukSeviyesi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EgzersizID");

                    b.ToTable("Egzersizler");
                });

            modelBuilder.Entity("SporBeslenmeWeb.Models.KasGruplari", b =>
                {
                    b.Property<int>("KasGrupID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KasGrupID"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KasGrupID");

                    b.ToTable("KasGruplari");
                });

            modelBuilder.Entity("SporBeslenmeWeb.Models.Tarifler", b =>
                {
                    b.Property<int>("TarifID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TarifID"));

                    b.Property<string>("Ad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GorselYolu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hazirlanis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KarbonhidratYuzdesi")
                        .HasColumnType("int");

                    b.Property<string>("Kategori")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Malzemeler")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProteinYuzdesi")
                        .HasColumnType("int");

                    b.Property<int>("YagYuzdesi")
                        .HasColumnType("int");

                    b.HasKey("TarifID");

                    b.ToTable("Tarifler");
                });
#pragma warning restore 612, 618
        }
    }
}
